import { normalizeFinding } from "../scanner-core/finding";
import { Finding, ScannerAdapter, ScanContext, Severity } from "../scanner-core/types";

interface UrlProbe {
  path: string;
  title: string;
  severity: Severity;
  category: string;
  marker?: RegExp;
  platformHint?: string;
  affectedDataType?: "pii" | "medical" | "financial" | "credential" | "customer-conversation" | "internal-business" | "unknown";
}

const INTERNAL_PATHS = [
  "/admin",
  "/dashboard",
  "/customer",
  "/customers",
  "/support",
  "/internal",
  "/settings",
  "/account",
  "/app"
];

const RESOURCE_PROBES: UrlProbe[] = [
  { path: "/robots.txt", title: "Robots file is publicly accessible", severity: "info", category: "indexability", marker: /Disallow|Allow|Sitemap/i },
  { path: "/sitemap.xml", title: "Sitemap is publicly accessible", severity: "low", category: "indexability", marker: /<urlset|<sitemapindex/i },
  { path: "/_next/static/chunks/main.js.map", title: "Source map may be publicly accessible", severity: "medium", category: "exposure", marker: /"sources"|"mappings"/i },
  { path: "/assets/index.js.map", title: "Source map may be publicly accessible", severity: "medium", category: "exposure", marker: /"sources"|"mappings"/i },
  { path: "/app.js.map", title: "Source map may be publicly accessible", severity: "medium", category: "exposure", marker: /"sources"|"mappings"/i },
  { path: "/error.log", title: "Log file may be publicly accessible", severity: "high", category: "exposure", marker: /error|exception|stack|trace/i },
  { path: "/vercel.svg", title: "Default Vercel asset detected", severity: "low", category: "platform", platformHint: "Vercel", marker: /svg/i },
  { path: "/replit.svg", title: "Default Replit asset detected", severity: "low", category: "platform", platformHint: "Replit", marker: /svg/i }
];

const PLATFORM_MARKERS: Array<{ platform: string; pattern: RegExp }> = [
  { platform: "Lovable", pattern: /lovable(?:\.dev)?|data-lovable/i },
  { platform: "Replit", pattern: /replit|replit\.app|repl\.co/i },
  { platform: "Base44", pattern: /base44/i },
  { platform: "Netlify", pattern: /netlify/i },
  { platform: "Vercel", pattern: /vercel|_next\/static/i },
  { platform: "Bolt", pattern: /bolt\.new|stackblitz/i },
  { platform: "v0", pattern: /v0\.dev|v0-generated/i },
  { platform: "Cursor", pattern: /cursor-generated|generated by cursor/i }
];

const SENSITIVE_DATA_MARKERS: Array<{ type: UrlProbe["affectedDataType"]; pattern: RegExp }> = [
  { type: "pii", pattern: /\b(?:email|phone|ssn|address|fullName)\b/i },
  { type: "medical", pattern: /\b(?:patient|diagnosis|medical|hipaa|prescription)\b/i },
  { type: "financial", pattern: /\b(?:credit\s*card|card\s*number|invoice\s*(?:id|number|#)|payment\s*(?:method|token|intent|secret)|bank\s*(?:account|routing)|stripe_customer)\b/i },
  { type: "customer-conversation", pattern: /\b(?:conversation|chat transcript|support ticket|message history)\b/i },
  { type: "internal-business", pattern: /\b(?:admin notes|internal|crm|customer list|dashboard)\b/i }
];

export const vibeUrlScanner: ScannerAdapter = {
  name: "vibe-public-exposure-url-scanner",
  async scan(context: ScanContext) {
    if (context.target.kind !== "url" || !context.httpClient) {
      return { findings: [] };
    }

    const findings: Finding[] = [];
    if (context.target.url.protocol !== "https:" && !isLocalDevelopmentUrl(context.target.url)) {
      findings.push(normalizeFinding({
        id: "vibe.url.https-not-used",
        title: "Target URL does not use HTTPS",
        severity: "high",
        confidence: "high",
        category: "configuration",
        vibeRiskCategory: "public-by-default-deployment",
        targetType: "url",
        sourceTool: "vibe-public-exposure-url-scanner",
        target: context.target.raw,
        endpoint: context.target.url.toString(),
        evidence: "The authorized target URL was provided over HTTP instead of HTTPS.",
        recommendation: "Serve the application over HTTPS and redirect HTTP to HTTPS.",
        verification: "Request the site over HTTP and confirm it redirects to HTTPS with HSTS on HTTPS responses."
      }));
    }

    const home = await context.httpClient.request("/", { method: "GET", bodySnippetLimit: 2048 });
    findings.push(...detectPlatformHints(context.target.raw, home.url, home.bodySnippet ?? ""));
    findings.push(...detectSensitiveDataIndicators(context.target.raw, home.url, home.bodySnippet ?? ""));

    for (const internalPath of INTERNAL_PATHS) {
      const response = await context.httpClient.request(internalPath, { method: "GET", bodySnippetLimit: 1024 });
      if (response.status >= 200 && response.status < 300 && !looksLikeLoginPage(response.bodySnippet ?? "")) {
        findings.push(normalizeFinding({
          id: "vibe.url.public-internal-page",
          title: "Internal-looking page is publicly reachable",
          severity: "high",
          confidence: "medium",
          category: "access-control",
          vibeRiskCategory: "public-sensitive-page",
          targetType: "url",
          sourceTool: "vibe-public-exposure-url-scanner",
          target: context.target.raw,
          endpoint: response.url,
          evidence: `GET ${internalPath} returned HTTP ${response.status} and did not look like an authentication challenge. Response body was not stored.`,
          authBoundaryRisk: true,
          recommendation: "Require server-side authentication and authorization for dashboard, admin, support, customer, and internal pages.",
          verification: "Request the path in an unauthenticated browser session and confirm it redirects to login or returns 401/403."
        }));
      }
    }

    for (const probe of RESOURCE_PROBES) {
      const response = await context.httpClient.request(probe.path, { method: probe.path.endsWith(".txt") || probe.path.endsWith(".xml") ? "GET" : "HEAD", bodySnippetLimit: 1024 });
      const body = response.bodySnippet ?? "";
      const accessible = response.status >= 200 && response.status < 300;
      const markerMatched = probe.marker ? probe.marker.test(body) || response.status === 200 : accessible;
      if (accessible && markerMatched) {
        findings.push(normalizeFinding({
          id: `vibe.url.${probe.category}`,
          title: probe.title,
          severity: probe.severity,
          confidence: "medium",
          category: probe.category === "platform" ? "configuration" : probe.category,
          vibeRiskCategory: probe.category,
          targetType: "url",
          sourceTool: "vibe-public-exposure-url-scanner",
          target: context.target.raw,
          endpoint: response.url,
          evidence: `${probe.path} returned HTTP ${response.status}. Raw response content was not stored.`,
          platformHint: probe.platformHint,
          affectedDataType: probe.affectedDataType,
          recommendation: recommendationForProbe(probe),
          verification: "Request the path again and confirm only intentional public content is accessible."
        }));
      }
    }

    return { findings };
  }
};

function detectPlatformHints(target: string, endpoint: string, body: string): Finding[] {
  return PLATFORM_MARKERS
    .filter((marker) => marker.pattern.test(body))
    .map((marker) => normalizeFinding({
      id: "vibe.url.platform-hint",
      title: `${marker.platform} platform hint detected`,
      severity: "info",
      confidence: "medium",
      category: "configuration",
      vibeRiskCategory: "platform-hint",
      targetType: "url",
      sourceTool: "vibe-public-exposure-url-scanner",
      target,
      endpoint,
      evidence: `The landing page contains a ${marker.platform} platform marker. Raw content was not stored.`,
      platformHint: marker.platform,
      recommendation: "Confirm the deployment platform configuration is intentional and does not expose default pages, debug pages, source maps, or public data stores.",
      verification: "Review platform settings for authentication, environment variables, public storage, and preview deployment exposure."
    }));
}

function detectSensitiveDataIndicators(target: string, endpoint: string, body: string): Finding[] {
  return SENSITIVE_DATA_MARKERS
    .filter((marker) => marker.pattern.test(body))
    .map((marker) => normalizeFinding({
      id: "vibe.url.sensitive-data-indicator",
      title: "Public page contains sensitive data exposure indicators",
      severity: "medium",
      confidence: "low",
      category: "exposure",
      vibeRiskCategory: "sensitive-data-indicator",
      targetType: "url",
      sourceTool: "vibe-public-exposure-url-scanner",
      target,
      endpoint,
      evidence: `A public page matched ${marker.type ?? "unknown"} exposure indicators. Raw sensitive content was not stored.`,
      affectedDataType: marker.type,
      recommendation: "Review whether the page exposes PII, medical, financial, customer conversation, or internal business data without authorization.",
      verification: "Confirm sensitive data is only returned after server-side authorization and field filtering."
    }));
}

function looksLikeLoginPage(body: string): boolean {
  return /\b(sign in|log in|login|auth|password|continue with|magic link)\b/i.test(body);
}

function isLocalDevelopmentUrl(url: URL): boolean {
  return /^(?:localhost|127(?:\.\d{1,3}){3}|\[?::1\]?)$/i.test(url.hostname);
}

function recommendationForProbe(probe: UrlProbe): string {
  if (probe.category === "indexability") {
    return "Review whether search indexing is intended. Avoid listing internal, dashboard, customer, or support paths in public robots or sitemap files.";
  }
  if (probe.category === "platform") {
    return "Remove default platform assets or pages when they reveal implementation details unnecessarily.";
  }
  return "Remove accidental public exposure and block source maps, logs, backups, and debug resources from production.";
}
